# Data Source Properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/speedywheels?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  sql:
    init:
      mode: never

 # Multipart settings
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update

# MVC Properties
  mvc:
    hidden-method:
      filter:
        enabled: true

# Email Sending
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:speedywheelsapp@gmail.com}
    password: ${MAIL_PASSWORD:ramo oxgd znyw vvrh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Email Recipient
email:
  recipient:
    address: ${EMAIL_RECIPIENT}

# Logging Levels
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

# Cloudinary
cloudinary:
  name: ${CLOUDINARY_NAME:db1rc9fon}
  api-key: ${CLOUDINARY_API_KEY:243925638474447}
  api-secret: ${CLOUDINARY_API_SECRET:tUEAVL6gWzGlllgMDLfHzDZFoH0}


# Administrator
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  first-name: ${ADMIN_FIRST_NAME:Ventsialav}
  last-name: ${ADMIN_LAST_NAME:Stoyanov}
  email: ${ADMIN_EMAIL:admin@example.com}
  age: ${ADMIN_AGE:28}
  city: ${ADMIN_CITY:Sofia}
  phone-number: ${ADMIN_PHONE_NUMBER:1234567890}
  profile-picture: ${ADMIN_PROFILE_PICTURE:https://res.cloudinary.com/db1rc9fon/image/upload/v1721171947/IMG_2073_jrmc8n.jpg}